apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-hello-world
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/ArunSonti/app-k8s-configs.git
    targetRevision: HEAD
    path: app-configs
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
