apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: app
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
      annotations:
        checksum/config: include (print $.Template.BasePath "/config-maps.yaml") . | sha256sum
    spec:
      containers:
      - name: hello-world
        image: arunsonti/hello-world-springboot-app:2.0
        envFrom:
          - configMapRef:
              name: hello-world
        ports:
        - containerPort: 8080
          protocol: TCP
