apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: hackathon
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      name: http
      port: 8003
      targetPort: 8080