apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: cache-sync-redis
  namespace: argo
spec:
  entrypoint: data-load
  spec:
  # must complete in 8h (28,800 seconds)
  activeDeadlineSeconds: 100
  # keep workflows for 1d (86,400 seconds)
  # ttlStrategy:
  #   secondsAfterCompletion: 300
  # delete all pods as soon as they complete
  podGC:
    strategy: OnPodCompletion

  templates:
  - name: data-load
    dag:
      tasks:
      - name: load-data-in-postgres
        template: echo
        arguments:
          parameters: [{name: message, value: Loading data in Postgres HI_Ref schema}]
      - name: load-data-in-redis
        depends: "load-data-in-postgres"
        template: echo
        arguments:
          parameters: [{name: message, value: Loading data in Redis}]
      - name: validate-postgres-data
        depends: "load-data-in-postgres"
        template: echo
        arguments:
          parameters: [{name: message, value: Validating-postgres-data}]
      - name: validating-redis-keys
        depends: "load-data-in-redis && validate-postgres-data"
        template: echo
        arguments:
          parameters: [{name: message, value: Validating-redis-keys}]

  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
