apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: load-workflow
  namespace: argo
spec:
  entrypoint: data-load
  templates:
  - name: data-load
    dag:
      tasks:
      - name: load-data-in-postgres
        template: echo
        arguments:
          parameters: [{name: message, value: Loading data in postgres hi_ref schema}]
      - name: load-data-in-redis
        depends: "load-data-in-postgres"
        template: echo
        arguments:
          parameters: [{name: message, value: Loading data in redis}]
      - name: validate-postgres-data
        depends: "load-data-in-postgres"
        template: echo
        arguments:
          parameters: [{name: message, value: Validating-postgres-data}]
      - name: validating-redis-keys
        depends: "load-data-in-redis && validate-postgres-data"
        template: echo
        arguments:
          parameters: [{name: message, value: Validating-redis-keys}]

  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
