apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: cache-sync-redis
  namespace: argo
spec:
  entrypoint: data-load
  spec:
  # must complete in below seconds
#   activeDeadlineSeconds: 100
  # keep workflows till below seconds
#   ttlStrategy:
#     secondsAfterCompletion: 200
  # delete all pods as soon as they complete
  podGC:
    strategy: OnPodCompletion

  templates:
  - name: data-load
    dag:
      tasks:
      - name: load-data-in-postgres
        template: echo
        arguments:
          parameters: [{name: message, value: Loading data in Postgres HI_Ref schema}]
      - name: load-data-in-redis
        depends: "validate-postgres-data"
        template: echo
        arguments:
          parameters: [{name: message, value: Loading data in Redis}]
      - name: validate-postgres-data
        depends: "load-data-in-postgres"
        template: echo
        arguments:
          parameters: [{name: message, value: Validating Postgres Data}]
      - name: place-holder-task
        depends: "validate-postgres-data"
        template: echo
        arguments:
          parameters: [{name: message, value: run this job after data load in postres}]
      - name: validating-redis-keys
        depends: "load-data-in-redis"
        template: echo
        arguments:
          parameters: [{name: message, value: Validating Redis Keys}]

  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
